# Session 3 - Übung 2

In [1]:
import pandas as pd

**Aufgabe 1:** Laden Sie die csv Datei sdf_ger.csv und speichern Sie diese in `sdf`. Schauen Sie sich die ersten 7 Zeilen an.

In [7]:
sdf = pd.read_csv('data/sdf_ger.csv')
sdf.head(7)

,country_name,country_text_id,e_regiongeo,year,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2x_delibdem,v2x_egaldem
0,Germany,DEU,1,1900,0.243,0.221,0.166,0.191,0.185
1,Germany,DEU,1,1901,0.242,0.222,0.167,0.190,0.176
2,Germany,DEU,1,1902,0.250,0.222,0.168,0.171,0.172
3,Germany,DEU,1,1903,0.245,0.219,0.169,0.177,0.171
4,Germany,DEU,1,1904,0.256,0.216,0.178,0.183,0.172
5,Germany,DEU,1,1905,0.253,0.210,0.176,0.181,0.172
6,Germany,DEU,1,1906,0.240,0.212,0.164,0.175,0.173

**Aufgabe 2:** Berechnen Sie den Mittelwert der Variable v2x_partipdem zwischen 1900 und 1950 und zwischen 1990 und 2018. Wie groß ist die Differenz dieser beiden Werte?

In [8]:
v2x_partipdem_1 = sdf[(sdf['year'] >= 1900) & (sdf['year'] <= 1950)]['v2x_partipdem'].mean()
v2x_partipdem_1

np.float64(0.22293617021276596)

In [5]:
v2x_partipdem_2 = sdf[(sdf['year'] >= 1990) & (sdf['year'] <= 2018)]['v2x_partipdem'].mean()
v2x_partipdem_2

np.float64(0.645)

In [6]:
v2x_partipdem_2 - v2x_partipdem_1

np.float64(0.42206382978723406)

**Aufgabe 3:** Wählen Sie die 5. bis 30. Zeile in sdf aus und speicher Sie diese Daten in sub_sdf. Schauen Sie sich den Index an. Reseten Sie den index.

In [9]:
sub_sdf = sdf.loc[4:31].copy()

In [10]:
sub_sdf.head()

,country_name,country_text_id,e_regiongeo,year,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2x_delibdem,v2x_egaldem
4,Germany,DEU,1,1904,0.256,0.216,0.178,0.183,0.172
5,Germany,DEU,1,1905,0.253,0.210,0.176,0.181,0.172
6,Germany,DEU,1,1906,0.240,0.212,0.164,0.175,0.173
7,Germany,DEU,1,1907,0.256,0.227,0.167,0.180,0.174
8,Germany,DEU,1,1908,0.243,0.217,0.160,0.173,0.170

In [11]:
sub_sdf.index

RangeIndex(start=4, stop=32, step=1)

In [12]:
sub_sdf = sub_sdf.reset_index(drop = True)

In [13]:
sub_sdf.head()

,country_name,country_text_id,e_regiongeo,year,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2x_delibdem,v2x_egaldem
0,Germany,DEU,1,1904,0.256,0.216,0.178,0.183,0.172
1,Germany,DEU,1,1905,0.253,0.210,0.176,0.181,0.172
2,Germany,DEU,1,1906,0.240,0.212,0.164,0.175,0.173
3,Germany,DEU,1,1907,0.256,0.227,0.167,0.180,0.174
4,Germany,DEU,1,1908,0.243,0.217,0.160,0.173,0.170

In [14]:
sub_sdf.index

RangeIndex(start=0, stop=28, step=1)

**Aufgabe 4**: Erstellen Sie eine neue Spalte in sub_sdf mit dem Namen 'delibdem_egaldem'. In dieser Spalte soll die Summe von delibdem und egaldem stehen.

In [15]:
sub_sdf['delibdem_egaldem'] = sub_sdf.v2x_delibdem + sub_sdf.v2x_egaldem

In [16]:
sub_sdf[["v2x_delibdem", "v2x_egaldem", 'delibdem_egaldem' ]].head()

   v2x_delibdem  v2x_egaldem  delibdem_egaldem
0         0.183        0.172             0.355
1         0.181        0.172             0.353
2         0.175        0.173             0.348
3         0.180        0.174             0.354
4         0.173        0.170             0.343

**Aufgabe 5:** Berechnen Sie den Mittelwert von v2x_libdem für jedes Land ab 2000 in `df`. Verwenden Sie dabei die `.groupby()` und `.mean()` Methode. Speichern Sie das Ergebnis in `libdem_2000`. 

- Welchen Typ hat dieses Objekt?

In [17]:
df = pd.read_csv('data/vdem/filtered_subset.csv')

In [18]:
df.head()

,country_name,country_text_id,e_regiongeo,year,v2x_polyarchy,v2x_libdem,v2x_partipdem,v2x_delibdem,v2x_egaldem,v2smprivex,v2smpolsoc,v2caviol,e_boix_regime
0,Mexico,MEX,17,1900,0.118,0.061,0.098,0.034,0.028,NaN,NaN,1.323,0.0
1,Mexico,MEX,17,1901,0.118,0.061,0.098,0.034,0.028,NaN,NaN,1.323,0.0
2,Mexico,MEX,17,1902,0.118,0.061,0.098,0.034,0.028,NaN,NaN,1.323,0.0
3,Mexico,MEX,17,1903,0.118,0.061,0.098,0.034,0.028,NaN,NaN,1.323,0.0
4,Mexico,MEX,17,1904,0.118,0.061,0.098,0.034,0.028,NaN,NaN,1.323,0.0

In [19]:
libdem_2000 = df[df.year >= 2000].groupby('country_name')['v2x_libdem'].mean()

In [20]:
libdem_2000[0:13]

country_name
Afghanistan    0.194200
Albania        0.429850
Algeria        0.140700
Angola         0.138450
Argentina      0.616750
Armenia        0.239150
Australia      0.828950
Austria        0.778350
Azerbaijan     0.071350
Bahrain        0.065056
Bangladesh     0.184200
Barbados       0.671150
Belarus        0.096150
Name: v2x_libdem, dtype: float64

In [21]:
type(libdem_2000)

pandas.core.series.Series

**Aufgabe 6:** Wandeln Sie libdem_2000 mit `.reset_index()` in eine DataFrame mit dem Name `libdem_2000_df` um.

In [22]:
libdem_2000_df = libdem_2000.reset_index()

In [23]:
libdem_2000_df.head()

  country_name  v2x_libdem
0  Afghanistan     0.19420
1      Albania     0.42985
2      Algeria     0.14070
3       Angola     0.13845
4    Argentina     0.61675

**Aufgabe 7:** Welchen Wert hat Bangladesh?

In [24]:
libdem_2000_df[libdem_2000_df.country_name == 'Bangladesh']

   country_name  v2x_libdem
10   Bangladesh      0.1842

**Aufgabe 8:** Welches Land hat den geringsten Wert? (`.sort_values()`)

In [25]:
libdem_2000_df.sort_values(by='v2x_libdem')

     country_name  v2x_libdem
47        Eritrea     0.00830
113   North Korea     0.01325
164  Turkmenistan     0.03105
133  Saudi Arabia     0.03445
171    Uzbekistan     0.04275
..            ...         ...
34     Costa Rica     0.83815
56        Germany     0.84425
115        Norway     0.85680
40        Denmark     0.86920
151        Sweden     0.87245

[179 rows x 2 columns]

**Aufgabe 9**: Berechnen Sie für jedes Land das minimum, maximum, Standardabweichung und Mittelwert. Arbeiten Sie dabei mit dem Datafram `df`.

1. Gruppieren
2. Variable auswählen
3. Aggregieren

Alle Schritte können verkettet werden.

In [26]:
df.groupby('country_name')[['v2x_polyarchy']].agg(['min', 'max', 'std', 'mean'])

             v2x_polyarchy
                       min    max       std      mean
country_name
Afghanistan          0.023  0.425  0.105902  0.128142
Albania              0.050  0.563  0.154186  0.245877
Algeria              0.044  0.372  0.114592  0.143608
Angola               0.009  0.386  0.095213  0.068042
Argentina            0.074  0.843  0.265407  0.450642
...                    ...    ...       ...       ...
Vietnam              0.095  0.313  0.044183  0.197613
Yemen                0.020  0.359  0.121251  0.113382
Zambia               0.041  0.537  0.166336  0.223945
Zanzibar             0.017  0.360  0.104111  0.107617
Zimbabwe             0.061  0.316  0.042862  0.245966

[183 rows x 4 columns]

**Aufgabe 10:** Welches Land weist die meisten Missings in der Variable `v2x_partipdem` im datafram `df` auf? 

1. Filtern der nan Zeilen
2. Gruppieren
3. Größe
4. Values sortieren

In [27]:
df[df.v2x_partipdem.isna()].groupby('country_name').size().sort_values(ascending=False)

country_name
Timor-Leste                   62
Honduras                      24
Libya                         23
Mozambique                    20
Luxembourg                    15
Egypt                         13
Uzbekistan                    12
Vanuatu                        6
Slovakia                       6
German Democratic Republic     4
El Salvador                    3
Republic of Vietnam            2
Albania                        2
Zimbabwe                       2
Nicaragua                      1
Tanzania                       1
Lebanon                        1
Turkmenistan                   1
Kazakhstan                     1
Jamaica                        1
dtype: int64